### ISSUE TITLE
Create a good CONTRIBUTION.md Guide

### ISSUE THREAD

**Issue by kunalagra** [Mind-Benders/.github#1]
We are looking for a well defined CONTRIBUTION.md file for the Organization that will serve as common for all the Repos across the organization. It should reflect about the core values of the organization and how anyone can help us by contributing to the project.

**Comment by ganesh-utla** [comment]
Can you assign me to this task!

**Comment by kunalagra** [comment]
Done

**Comment by AdarshCoder397** [comment]
Hey @kunalagra , I can work on this!!

**Comment by kunalagra** [comment]
> Hey @kunalagra , I can work on this!!

Already been solved. I will adding more Issues today so you may try them.
