### ISSUE TITLE
 Create CODE_OF_CONDUCT.md Guide

### ISSUE THREAD

**Issue by kunalagra** [Mind-Benders/.github#2]
We are looking for a well defined  CODE_OF_CONDUCT.md file for the Organization that will serve as common for all the Repos across the organization. 

The file should layout brief Code of Conduct for anyone looking forward to contribute with Do's & Don't to help them navigate on contributing to the repos in easy manner.

**Comment by ganesh-utla** [comment]
I would like to do this task..

**Comment by kunalagra** [comment]
You have been assigned the Issue
